Update MotorControl.ino
Release Version 1.1 
28 Feb 2021
Fixed Compilation error: added Missing "}"
Need to fix bugs in this version -will be fixed soon.